---
# This tasks applies basic customization
- name: "Create home directory layout"
  file:
    path: "{{ lookup('env','HOME') + '/Documents/' + item }}"
    state: directory
  with_items:
    - HackTheBox/Challenges
    - HackTheBox/Machines
    - TryHackMe
    - CTFs
- name: "Change default shell to bash"
  block:
  - name: Change default shell to regular user
    become: yes
    command: "{{ 'chsh -s /bin/bash ' + kali_user }}" 
  - name: Change default shell to root
    become: yes
    command: chsh -s /bin/bash
- name: "Replace bashrc"
  block:
    - name: "Replace user bashrc"
      copy: 
        src: "files/.bashrc"
        dest: "{{ lookup('env','HOME') + '/.bashrc'}}"
        remote_src: yes
    - name: "Replace root bashrc"
      become: yes
      copy: 
        src: "files/.bashrc"
        dest: "{{ lookup('env','HOME') + '/.bashrc'}}"
        remote_src: yes