---
# This tasks applies basic customization
- name: "Create home directory layout"
  file:
    path: "{{ lookup('env','HOME') + '/Documents/' + item }}"
    state: directory
  with_items:
    - HackTheBox/Challenges
    - HackTheBox/Machines
    - TryHackMe
    - CTFs
- name: "Replace bashrc"
  block:
    - name: "Replace user bashrc"
      copy: 
        src: "files/.bashrc"
        dest: "{{ lookup('env','HOME') + '/.bashrc'}}"
        remote_src: yes
    - name: "Replace root bashrc"
      become: true
      copy: 
        src: "files/.bashrc"
        dest: "{{ lookup('env','HOME') + '/.bashrc'}}"
        remote_src: yes
- name: "Setup tmux"
  block:
    - name: Change default shell to regular user
      become: true
      command: "{{ 'chsh -s /usr/bin/tmux ' + kali_user }}" 
    - name: Change default shell to root
      become: true
      command: chsh -s /bin/bash
    - name: "Replace user .tmux.conf"
      copy: 
        src: "files/.tmux.conf"
        dest: "{{ lookup('env','HOME') + '/.tmux.conf'}}"
        remote_src: yes